export * from "./coordinator-manager"
export * from "./types"
export * from "./architecture.worker"
export * from "./product-manager.worker"
export * from "./backend.worker"
export * from "./frontend.worker"
export * from "./mobile.worker"
export * from "./data-scientist.worker"
export * from "./security.worker"
export * from "./test.worker"
export * from "./devops.worker"
export * from "./reviewer.worker"
export * from "./librarian.worker"
export * from "./forensic.worker"
export * from "./secrets"
export * from "./tool-bridge"
export * from "./plan-parser"
// subagent-registry re-exports from subagent-prompts, so only export from registry to avoid duplicates
export * from "./subagent-registry"
export { discoverDynamicSubAgents } from "./db-discovery"
