// Auto-generated by scripts/generate-ui-bundle.ts before binary compilation.
// This stub is committed to git (embeddedUI.size === 0 → uses filesystem dist/ui).
export const embeddedUI = new Map<string, { data: Buffer; mime: string }>();
