// Auto-generated by scripts/generate-ui-bundle.ts before binary compilation.
// This stub is published with the npm package (embeddedUI.size === 0 → uses filesystem).
export const embeddedUI = new Map<string, { data: Buffer; mime: string }>();
