export { openSessionDb, getSessionDb, closeSessionDb, closeAllSessionDbs } from "./client.ts"
export { SESSION_SCHEMA } from "./schema.ts"
export { SessionsRepo } from "./repos/sessions.ts"
export { MessagesRepo } from "./repos/messages.ts"
export { AgentContextRepo } from "./repos/agent-context.ts"
export { AgentConflictsRepo } from "./repos/agent-conflicts.ts"
export { AgentAwarenessRepo } from "./repos/agent-awareness.ts"
export { CheckpointsRepo } from "./repos/checkpoints.ts"
export { AdrsRepo } from "./repos/adrs.ts"
export { FileRisksRepo } from "./repos/file-risks.ts"

export type { Session } from "./repos/sessions.ts"
export type { Message } from "./repos/messages.ts"
export type { ContextEntry, ContextType, ContextStatus, ContextScope, WorkerAwareness } from "./repos/agent-context.ts"
export type { AgentConflict, ConflictType, ConflictSeverity } from "./repos/agent-conflicts.ts"
export type { AwarenessEntry, WorkerStatus } from "./repos/agent-awareness.ts"
export type { Checkpoint, CheckpointFile, CheckpointOperation } from "./repos/checkpoints.ts"
export type { Adr, AdrStatus } from "./repos/adrs.ts"
export type { FileRisk, RiskLevel } from "./repos/file-risks.ts"
